config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  get 'events', to: 'events#index'
  get 'events/:id', to: 'events#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entrant.rb
class Entrant < ApplicationRecord
  belongs_to :event
  belongs_to :player

  validates :player, uniqueness: { scope: :event }

  delegate :full_name, to: :player
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, uniqueness: true

  has_many :entrants
  has_many :players, through: :entrants
end

app/models/player.rb
class Player < ApplicationRecord
  validates :full_name, uniqueness: true

  has_many :entrants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def show
    @event = Event.preload(:players).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def humanize_money_amount(amount)
    "$#{number_with_delimiter(amount.to_i, delimiter: ',')}"
  end

  def humanize_place(place)
    place = case place % 10
    when 1 then "#{place}<span class='sequent-end'>ST</span>"
    when 2 then "#{place}<span class='sequent-end'>ND</span>"
    when 3 then "#{place}<span class='sequent-end'>RD</span>"
    else "#{place}<span class='sequent-end'>TH</span>" end

    place.html_safe
  end
end

app/views/events/index.html.erb
<div class="events-container">
  <div class="event-container-header-logo"><img src="/img/logo.png" alt="logo" width="211" height="63"></div>
  <table class="events-container-table">
    <thead class="events-container-table-head">
      <tr>
        <th>Event Name</th>
        <th>Prize</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
    <% @events.each do |event| %>
      <tr>
        <td class="event-name">
          <%= link_to event.name, "events/#{event.id}" %>
        </td>
        <td class="event-prize-pool"><%= humanize_money_amount(event.prize_pool) %></td>
        <td class="event-date"><%= event.holding_date %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="events-container-table-footer"></div>
</div>

app/views/events/show.html.erb
<div class="event-container">
  <div class="event-container-header">
    <span class="event-container-header-logo"><img src="/img/logo.png" alt="logo" width="211" height="63"></span>
    <span class="event-container-header-text"><%= @event.name.sub(/.*?#/, '#') %></span>
  </div>

  <table class="event-container-table">
    <tbody>
    <% @event.entrants.each do |entrant| %>
      <tr>
        <td class="entrant-place"><%= humanize_place(entrant.place) %></td>
        <td class="entrant-name"><%= entrant.full_name %></td>
        <td class="entrant-prize-pool"><%= humanize_money_amount(entrant.prize_pool) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <div class="event-container-top-footer">
    <%= @event.entrants_count %> ENTRIES - <%= humanize_money_amount(@event.prize_pool) %> PRIZE POOL
  </div>
  <div class="event-container-footer">
    <a href="<%= events_path %>">
      <img src="/img/container-close-btn.png" alt="logo" width="166" height="166">
    </a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventDisplayer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>